import {listInvoiceEndpointListInvoicePaginatedResponseModel} from 'packages/models/src/listInvoiceEndpointListInvoicePaginatedResponseModel.generated.ts'
import {useQuery, queryOptions, keepPreviousData} from '@tanstack/react-query'
import {apiFetch, buildUrl} from '@/lib/api/client'

export type UseGetApiInvoicesArgs = {Authorization: string, before?: string | undefined, after?: string | undefined, limit?: number | undefined, sortOrder?: ('ASC' | 'DESC') | undefined, sortBy?: string | undefined, invoiceStatus?: string | undefined, invoicePaymentStatus?: string | undefined, customerId?: string | undefined, billingScheduleId?: string | undefined, dueBefore?: string | undefined, dueAfter?: string | undefined, sentBefore?: string | undefined, sentAfter?: string | undefined, invoiceBefore?: string | undefined, invoiceAfter?: string | undefined, excludeZeroQuantity?: boolean | undefined, invoiceCurrency?: string | undefined, search?: string | undefined, invoiceNumber?: string | undefined, netTotal?: number | undefined, excludeInvoiceStatus?: string | undefined, excludeInvoicePaymentStatus?: string | undefined, excludeCustomerId?: string | undefined, excludeBillingScheduleId?: string | undefined, excludeInvoiceCurrency?: string | undefined, excludeInvoiceNumber?: string | undefined, excludeNetTotal?: number | undefined, excludeSearch?: string | undefined, 'sequence-version'?: '2024-07-30' | undefined};

export const getApiInvoicesQueryOptions = (args: UseGetApiInvoicesArgs) =>
      queryOptions({
        queryKey: ['GET /invoices', 'Invoices', args.Authorization, args.before, args.after, args.limit, args.sortOrder, args.sortBy, args.invoiceStatus, args.invoicePaymentStatus, args.customerId, args.billingScheduleId, args.dueBefore, args.dueAfter, args.sentBefore, args.sentAfter, args.invoiceBefore, args.invoiceAfter, args.excludeZeroQuantity, args.invoiceCurrency, args.search, args.invoiceNumber, args.netTotal, args.excludeInvoiceStatus, args.excludeInvoicePaymentStatus, args.excludeCustomerId, args.excludeBillingScheduleId, args.excludeInvoiceCurrency, args.excludeInvoiceNumber, args.excludeNetTotal, args.excludeSearch, args.'sequence-version'],
        queryFn: () => apiFetch(buildUrl('/invoices', { before: args.before, after: args.after, limit: args.limit, sortOrder: args.sortOrder, sortBy: args.sortBy, invoiceStatus: args.invoiceStatus, invoicePaymentStatus: args.invoicePaymentStatus, customerId: args.customerId, billingScheduleId: args.billingScheduleId, dueBefore: args.dueBefore, dueAfter: args.dueAfter, sentBefore: args.sentBefore, sentAfter: args.sentAfter, invoiceBefore: args.invoiceBefore, invoiceAfter: args.invoiceAfter, excludeZeroQuantity: args.excludeZeroQuantity, invoiceCurrency: args.invoiceCurrency, search: args.search, invoiceNumber: args.invoiceNumber, netTotal: args.netTotal, excludeInvoiceStatus: args.excludeInvoiceStatus, excludeInvoicePaymentStatus: args.excludeInvoicePaymentStatus, excludeCustomerId: args.excludeCustomerId, excludeBillingScheduleId: args.excludeBillingScheduleId, excludeInvoiceCurrency: args.excludeInvoiceCurrency, excludeInvoiceNumber: args.excludeInvoiceNumber, excludeNetTotal: args.excludeNetTotal, excludeSearch: args.excludeSearch }), listInvoiceEndpointListInvoicePaginatedResponseModel, { method: 'GET' }),
        placeholderData: keepPreviousData
      });

export const useGetApiInvoices = (args: UseGetApiInvoicesArgs) => useQuery(getApiInvoicesQueryOptions(args));
