import { z } from "zod";

export type NotificationType =
  | "CUSTOMER_CREATED"
  | "CUSTOMER_UPDATED"
  | "CUSTOMER_ARCHIVED"
  | "INVOICE_CREATED"
  | "INVOICE_ISSUED"
  | "INVOICE_UPDATED"
  | "INTEGRATION_SYNC_COMPLETED"
  | "INTEGRATION_WEBHOOK_HANDLED"
  | "MERCHANT_UPDATED"
  | "BILLING_SCHEDULE_CREATED"
  | "BILLING_SCHEDULE_UPDATED"
  | "BILLING_SCHEDULE_ARCHIVED"
  | "CREDIT_NOTE_CREATED"
  | "CREDIT_NOTE_UPDATED"
  | "CREDIT_NOTE_ISSUED"
  | "QUOTE_PUBLISHED"
  | "QUOTE_ACCEPTED"
  | "QUOTE_SIGNED"
  | "INVOICE_REMINDER_SENT"
  | "WATCHTOWER_TASK_ASSIGNED";

export const notificationType = z.enum([
  "CUSTOMER_CREATED",
  "CUSTOMER_UPDATED",
  "CUSTOMER_ARCHIVED",
  "INVOICE_CREATED",
  "INVOICE_ISSUED",
  "INVOICE_UPDATED",
  "INTEGRATION_SYNC_COMPLETED",
  "INTEGRATION_WEBHOOK_HANDLED",
  "MERCHANT_UPDATED",
  "BILLING_SCHEDULE_CREATED",
  "BILLING_SCHEDULE_UPDATED",
  "BILLING_SCHEDULE_ARCHIVED",
  "CREDIT_NOTE_CREATED",
  "CREDIT_NOTE_UPDATED",
  "CREDIT_NOTE_ISSUED",
  "QUOTE_PUBLISHED",
  "QUOTE_ACCEPTED",
  "QUOTE_SIGNED",
  "INVOICE_REMINDER_SENT",
  "WATCHTOWER_TASK_ASSIGNED",
]);
